schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    VpcEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        default_cidr_block:
          type: string
          description: "This CIDR range for your VPC"
          default: 192.168.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
